### ISSUE TITLE
styling for reviewer

### ISSUE THREAD

**Issue by Praven18** [Praven18/Reviewership#21]
Styling for side content needs to be done. Card styling is more or less done. Ask me if you want to change. You all need to add some stuff to the side content as well. And the styling for  the date form

**Comment by nbanko** [comment]
Performed first styling pass to side bar and cards. Date picker still needs styled

**Comment by nbanko** [comment]
Changes were commited

**Comment by nbanko** [comment]
submitted pull request for completed design of reviewer
